/**
 * GitHub integration layer.
 *
 * Creates issues from tickets, creates stacked PRs from bookmarks,
 * pushes branches, updates PR descriptions, and links issues to PRs.
 * All operations use the `gh` CLI.
 */
import { execGH, execJJ, rootDir } from "./utils";
import type { DomainConfig } from "./domains";

export interface GHIssue {
  number: number;
  url: string;
  title: string;
  ticketId: string;
}

export interface GHPR {
  number: number;
  url: string;
  branch: string;
  ticketId: string;
}

/**
 * Sync all tickets to GitHub issues.
 * Creates issues that don't exist yet, updates existing ones.
 * Returns a map of ticketId -> issue number.
 */
export function syncTicketsToIssues(
  tickets: Array<{ id: string; title: string; description: string; dependencies: string[]; type: string }>,
  domain: DomainConfig
): Map<string, number> {
  const issueMap = new Map<string, number>();

  // List existing issues with our label to avoid duplicates
  const existingRaw = execGH([
    "issue", "list",
    "--label", domain.githubLabel,
    "--state", "all",
    "--limit", "500",
    "--json", "number,title,body",
  ]);
  const existing: Array<{ number: number; title: string; body: string }> = JSON.parse(existingRaw || "[]");

  // Build a lookup by ticket ID embedded in the issue body
  const existingByTicketId = new Map<string, number>();
  for (const issue of existing) {
    const match = issue.body?.match(/<!-- ticket-id: ([^\s]+) -->/);
    if (match) {
      existingByTicketId.set(match[1], issue.number);
    }
  }

  for (const ticket of tickets) {
    const existingNumber = existingByTicketId.get(ticket.id);

    if (existingNumber) {
      issueMap.set(ticket.id, existingNumber);
      continue;
    }

    // Create new issue
    const depText = ticket.dependencies.length > 0
      ? `\n\n**Dependencies:** ${ticket.dependencies.map((d) => `\`${d}\``).join(", ")}`
      : "";

    const body = `<!-- ticket-id: ${ticket.id} -->
## ${ticket.title}

**Type:** ${ticket.type}
**Domain:** ${domain.name}

${ticket.description}${depText}

---
_Auto-generated by smithers workflow_`;

    try {
      const result = execGH([
        "issue", "create",
        "--title", `[${domain.id}] ${ticket.title}`,
        "--body", body,
        "--label", domain.githubLabel,
      ]);
      // Parse issue URL to get number
      const numMatch = result.match(/\/issues\/(\d+)/);
      if (numMatch) {
        issueMap.set(ticket.id, parseInt(numMatch[1], 10));
      }
    } catch (err) {
      console.error(`Failed to create issue for ${ticket.id}:`, err);
    }
  }

  return issueMap;
}

/**
 * Push a bookmark to the remote as a git branch.
 */
export function pushBookmark(bookmarkName: string, cwd?: string): void {
  execJJ(["git", "push", "--bookmark", bookmarkName], cwd || rootDir());
}

/**
 * Push all bookmarks matching a prefix.
 */
export function pushAllBookmarks(prefix: string, cwd?: string): void {
  // Get all bookmarks matching prefix
  const bookmarksRaw = execJJ(
    ["bookmark", "list", "--all", "-T", 'if(!remote, name ++ "\\n")'],
    cwd || rootDir()
  );
  const bookmarks = bookmarksRaw.split("\n").filter((b) => b.startsWith(prefix));

  for (const bookmark of bookmarks) {
    try {
      pushBookmark(bookmark, cwd);
    } catch (err) {
      console.error(`Failed to push bookmark ${bookmark}:`, err);
    }
  }
}

/**
 * Create a PR for a ticket's bookmark, stacked on the appropriate base.
 * Returns the PR number and URL.
 */
export function createPR(
  ticket: { id: string; title: string; description: string; dependencies: string[] },
  domain: DomainConfig,
  issueNumber?: number
): GHPR | null {
  const branch = `${domain.bookmarkPrefix}${ticket.id}`;

  // Determine the base branch (stack on last dependency or main)
  const deps = ticket.dependencies || [];
  const baseBranch = deps.length > 0
    ? `${domain.bookmarkPrefix}${deps[deps.length - 1]}`
    : "main";

  // Check if PR already exists for this branch
  try {
    const existingPR = execGH([
      "pr", "list",
      "--head", branch,
      "--json", "number,url",
      "--limit", "1",
    ]);
    const parsed = JSON.parse(existingPR || "[]");
    if (parsed.length > 0) {
      return {
        number: parsed[0].number,
        url: parsed[0].url,
        branch,
        ticketId: ticket.id,
      };
    }
  } catch {}

  // Push the branch first
  try {
    pushBookmark(branch);
  } catch (err) {
    console.error(`Failed to push ${branch}:`, err);
    return null;
  }

  // Create PR
  const closesText = issueNumber ? `\n\nCloses #${issueNumber}` : "";
  const body = `## ${ticket.title}

${ticket.description}${closesText}

---
_Auto-generated by smithers workflow_
**Domain:** ${domain.name}
**Ticket:** \`${ticket.id}\``;

  try {
    const result = execGH([
      "pr", "create",
      "--title", `[${domain.id}] ${ticket.title}`,
      "--body", body,
      "--base", baseBranch,
      "--head", branch,
      "--label", domain.githubLabel,
    ]);
    const numMatch = result.match(/\/pull\/(\d+)/);
    if (numMatch) {
      return {
        number: parseInt(numMatch[1], 10),
        url: result.trim(),
        branch,
        ticketId: ticket.id,
      };
    }
  } catch (err) {
    console.error(`Failed to create PR for ${ticket.id}:`, err);
  }

  return null;
}

/**
 * Update an existing PR's body or title.
 */
export function updatePR(prNumber: number, updates: { title?: string; body?: string }): void {
  const args = ["pr", "edit", String(prNumber)];
  if (updates.title) args.push("--title", updates.title);
  if (updates.body) args.push("--body", updates.body);
  execGH(args);
}

/**
 * Add a comment to a PR.
 */
export function commentOnPR(prNumber: number, comment: string): void {
  execGH(["pr", "comment", String(prNumber), "--body", comment]);
}

/**
 * Add a comment to an issue.
 */
export function commentOnIssue(issueNumber: number, comment: string): void {
  execGH(["issue", "comment", String(issueNumber), "--body", comment]);
}

/**
 * Close a GitHub issue.
 */
export function closeIssue(issueNumber: number): void {
  execGH(["issue", "close", String(issueNumber)]);
}
